project:
  type: book
  output-dir: ../docs

book:
  title: "Sequential Conditional (Marginally Optimal) Transport on Probabilistic Graphs for Interpretable Counterfactual Fairness"
  author:
  - name: Arthur Charpentier
    orcid: 0000-0003-3654-6286
    affiliations:
      - name: Université du Québec à Montréal
  - name: Agathe Fernandes Machado
    orcid: 0009-0002-9743-9708
    affiliations:
      - name: Université du Québec à Montréal
  - name: Ewen Gallic
    orcid: 0000-0003-3740-2620
    affiliations:
      - name: Aix-Marseille School of Economics, Aix-Marseille Univ.
  date: "8/6/2024"
  chapters:
    - index.qmd
    - part: I. Optimal Transport
      chapters:
      - optimal-transport.qmd
    - part: II. Simulations
      chapters:
        - gaussian.qmd
        - transport-fast-grid.qmd
        - algorithm-3.qmd
    - part: III. Counterfactuals with Law Dataset
      chapters:
      - data.qmd
      - classifier.qmd
      - cf-naive.qmd
      - cf-fairadapt.qmd
      - cf-ot.qmd
      - cf-seq-transport.qmd
      - cf-comparison.qmd
    - part: IV. Counterfactuals with Other Datasets
      chapters:
      - example-adult.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/fer-agathe/sequential_transport
        aria-label: GitHub

bibliography: ./biblio.bib

fig-cap-location: top

format:
  html:
    theme: litera
    html-math-method: mathjax
    include-in-header:
    - file: mathjax-color.html

filters:
  - pseudocode

editor: source
